# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import waterlevel_pb2 as waterlevel__pb2


class WaterLevelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetData = channel.unary_unary(
                '/waterlevel.WaterLevel/GetData',
                request_serializer=waterlevel__pb2.GetDataRequest.SerializeToString,
                response_deserializer=waterlevel__pb2.GetDataReply.FromString,
                )


class WaterLevelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetData(self, request, context):
        """Get Data beginning from timetsamp till now
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WaterLevelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=waterlevel__pb2.GetDataRequest.FromString,
                    response_serializer=waterlevel__pb2.GetDataReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'waterlevel.WaterLevel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WaterLevel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/waterlevel.WaterLevel/GetData',
            waterlevel__pb2.GetDataRequest.SerializeToString,
            waterlevel__pb2.GetDataReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
