# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waterlevel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10waterlevel.proto\x12\nwaterlevel\"-\n\x0eGetDataRequest\x12\x1b\n\x13\x62\x65ginning_timestamp\x18\x01 \x01(\x05\"\x1c\n\x0cGetDataReply\x12\x0c\n\x04json\x18\x01 \x01(\t2M\n\nWaterLevel\x12?\n\x07GetData\x12\x1a.waterlevel.GetDataRequest\x1a\x18.waterlevel.GetDataReplyb\x06proto3')



_GETDATAREQUEST = DESCRIPTOR.message_types_by_name['GetDataRequest']
_GETDATAREPLY = DESCRIPTOR.message_types_by_name['GetDataReply']
GetDataRequest = _reflection.GeneratedProtocolMessageType('GetDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDATAREQUEST,
  '__module__' : 'waterlevel_pb2'
  # @@protoc_insertion_point(class_scope:waterlevel.GetDataRequest)
  })
_sym_db.RegisterMessage(GetDataRequest)

GetDataReply = _reflection.GeneratedProtocolMessageType('GetDataReply', (_message.Message,), {
  'DESCRIPTOR' : _GETDATAREPLY,
  '__module__' : 'waterlevel_pb2'
  # @@protoc_insertion_point(class_scope:waterlevel.GetDataReply)
  })
_sym_db.RegisterMessage(GetDataReply)

_WATERLEVEL = DESCRIPTOR.services_by_name['WaterLevel']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETDATAREQUEST._serialized_start=32
  _GETDATAREQUEST._serialized_end=77
  _GETDATAREPLY._serialized_start=79
  _GETDATAREPLY._serialized_end=107
  _WATERLEVEL._serialized_start=109
  _WATERLEVEL._serialized_end=186
# @@protoc_insertion_point(module_scope)
